services:
  mysql:
    image: mysql:8.0
    container_name: mysql_biblio
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 13135690
      MYSQL_DATABASE: db_biblio
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpass
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 